### ISSUE TITLE
Introduce API to Delegate Mint NFT

### ISSUE THREAD

**Issue by thisisommore** [Weareflexable/Superiad#1]

**Comment by Shachindra** [comment]
Accept network, contractAddress, MetadataURI and customerID as request.
The contract address would be configured into the database and if the network and contractAddress matches then the delegate mint should result in success.

**Comment by thisisommore** [comment]
Currently network is already there in the API `matic/delegate`. Should we store contract address with the network and then check it?
Also what if it doesn't matches, we basically not go further and throw error to client right?
